### ISSUE TITLE
Vins which have same numeric 0-9 on each bit can bypass validation

### ISSUE THREAD

**Issue by jter** [h3/python-libvin#21]
eg:
``` python
>>> from libvin.decoding import Vin
>>>
>>> v = Vin('1' * 17)
>>> v.is_valid
True
```
`'1' * 17` can bypass the checking algorithm, Is this behavior correct?

**Comment by h3** [comment]
The VIN format standard is not well defined and change from country/time period to another.

That said I checked with another VIN validation library and they also consider a VIN consisting only of "1" as valid so I will close this issue.

Feel free to reopen if you find concrete proof that it should not be a valid VIN.


https://formvalidation.io/guide/validators/vin/
