### ISSUE TITLE
Norwegian ministry of motor vehicles fork

### ISSUE THREAD

**Issue by mercion** [h3/python-libvin#22]
Ive forked this repo and added in a quick decoder to pull information about the car from the Norwegian ministry of motor vehicles. Wondering if i should merge back into here. Seems a pity to have multiple forks doing the same things. 

Only downside is that it will only work with VINs to cars registered in Norway

**Comment by mercion** [comment]
Fork with Norwegian DMV ... https://github.com/mercion/python-libvin

**Comment by h3** [comment]
This project is on life support, but I'll gladly merge anything useful as long as it doesn't introduce bugs ;)

**Comment by h3** [comment]
Create a PR, I'll merge it.
