### ISSUE TITLE
Mexico, Costa Rica, and Cayman Islands have same key

### ISSUE THREAD

**Issue by Solanar** [h3/python-libvin#6]
In [static.py](/h3/python-libvin/blob/master/libvin/static.py), lines 131-138, Mexico, Costa Rica, and the Cayman Islands are defined with the same key of '3'.

These should be collapsed from:

    '3': {'region': 'north_america', 'countries': {
            'ABCDEFGHIJKLMNOPQRSTUVW': 'Mexico'}},

    '3': {'region': 'north_america', 'countries': {
            'XYZ1234567': 'Costa Rica'}},

    '3': {'region': 'north_america', 'countries': {
            '890': 'Cayman Islands'}},

To:

    '3': {'region': 'north_america', 'countries': {
            'ABCDEFGHIJKLMNOPQRSTUVW': 'Mexico',
            'XYZ1234567': 'Costa Rica',
            '890': 'Cayman Islands'}},

**Comment by dankegel** [comment]
I think this is now fixed.  Solanar, can you retest?

**Comment by Solanar** [comment]
Looks good to me, I don't think I had tests for this specific case, just noticed the issue. As long as you're sure the `3` should be taken out of Costa Rica and a `3` added to Mexico. I'm not sure where the numbers come from.
