### ISSUE TITLE
Provide 'make' attribute

### ISSUE THREAD

**Issue by dankegel** [h3/python-libvin#9]
The 'manufacturer' attribute exists, but is not tested.
The tests have 'make' data, but no 'make' attribute is implemented.

Since 'make' can be derived fairly easily from 'manufacturer' and the vin,
let's implement a test for the 'make' attribute in the test data,
and will a 'make' attribute into being.

A first draft implementation with tests is available at https://github.com/h3/python-libvin/pull/8 
That pull request is good enough to get the make right about 90% of the time against a known good database.  Getting to 100% right will be a never ending struggle :-)

**Comment by h3** [comment]
Merged !
